### PR TITLE
Fix double exit bug in parallel pipelines

### LINKED ISSUE #736: self.running_procs becomes negative, leading to AssertionError
Possibly low priority since I only found the problem while fixing another bug. Minimal test case:
```sh
echo "abc" > /tmp/data.txt
cat /tmp/data.txt
echo
echo
echo
```

Exception:
```python
Traceback (most recent call last):
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 535, in <module>
    main()
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 531, in main
    scheduler.run()
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 510, in run
    self.parse_and_run_cmd(input_cmd)
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 444, in parse_and_run_cmd
    response = self.compile_and_add(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 289, in compile_and_add
    self.wait_unsafe()
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 433, in wait_unsafe
    assert self.running_procs == 1
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Checking if self.running_procs already equals zero before decrementing it in `remove_process` does solve the immediate issue, but ideally the number should already match up.

### PR DESCRIPTION
**Pull request by BolunThompson**
Fixes #736, #738. This wasn’t a problem on Ubuntu 20.04 because the EXIT handler wasn’t called (for no obvious reason), so it only exited once.

### CODE REVIEW

File: compiler/pash_runtime.sh [hunk 1]
```diff
@@ -141,7 +141,7 @@ else
         pash_redir_output echo "$$: (5) BaSh script exited with ec: $pash_runtime_final_status"
     else 
         function run_parallel() {
-            trap inform_daemon_exit SIGTERM SIGINT EXIT
+            trap inform_daemon_exit SIGTERM SIGINT
             export SCRIPT_TO_EXECUTE="$pash_script_to_execute"
             source "$RUNTIME_DIR/pash_restore_state_and_execute.sh"
             inform_daemon_exit
```
Comment (angelhof) [inline compiler/pash_runtime.sh:147]: Maybe the best solution would be to leave the trap as is, and remove the inform at the end of the call to run_parallel? This would make sure that we only call `inform_daemon_exit` once (I wonder whether the current implementation allows a subtle corner case now where SIGTERM is received while we are in inform). 

Based on your explanation (EXIT not being called on Ubuntu 20) my proposed fix shouldn't work on Ubuntu 20, so if we agree that this would be a better fix but it doesn't work on Ubuntu 20, let's leave a comment in the code to remember that we have it at the end and at the trap because for some reason the trap is not properly triggered, but if it was, that is how we would like to implement it

**Review by angelhof — APPROVED** [review]
Could you add read my comment and if you agree add a comment in the code so that we remember that? After this is done (or if my comment doesn't make sense) we will merge :)

File: compiler/pash_runtime.sh (hunk 1 above)
Comment (BolunThompson) [reply compiler/pash_runtime.sh:147]: That’d be the best solution, but it doesn’t work, unfortunately. State of the repo after the first failed CI run: https://github.com/binpash/pash/pull/739/files/509fcf00f62edd210d969708dfee0d26e4088919

I’ll add a comment mentioning this. I can add a quick check in inform_daemon_exit as for whether exit it’s been called already to avoid the sigterm corner-case, which’d avoid a future bug like this.

Comment (angelhof) [reply compiler/pash_runtime.sh:147]: A comment should be fine :) No need to solve it since it wasn't solved previously either!
